apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-3yuv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-3yuv
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-3yuv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-3yuv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-3yuv
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-xstv-tenant/rhtap-demo-app/hacbs-test-project-3yuv@sha256:fc0b4d6f75f6dc0838a20d9d7b1b93345a034e4f602fb36d7bc65bf3d49ac674
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
